garagesite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^garage/', include('garage.urls', namespace='garage')),
    url(r'^admin/', include(admin.site.urls)),
]

mainsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('robox.urls')),
]

robox/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView
from rest_framework import routers

from robox.views import web, api, docs

router = routers.SimpleRouter()
router.register(r'api/files', api.FileViewSet, base_name='file')

urlpatterns = router.urls + [
    # URLs for the webapp.
    url(r'^upload/$', web.UploadView.as_view(), name="upload"),
    url(r'^view/(?P<barcode>\S+)/$', web.view_by_barcode, name="view"),
    url(r'^upload/(?P<barcode>\S+)/$', web.upload_by_barcode, name="upload_barcode"),
    url(r'^view/$', web.index, name="index"),
    url(r'^delete/(?P<pk>[0-9]+)/$', web.FileDelete.as_view(), name='delete_file'),
    url(r'^search/$', web.search, name="search"),
    url(r'^file/(?P<pk>\S+)/$', web.download_file, name='download'),
    url(r'^$', RedirectView.as_view(url='/view/', permanent=True), name='root'),

    # URLS for the documentation
    url(r'^docs/$', docs.index, name="docs_index"),
    url(r'^docs/api/$', docs.api, name="docs_api"),
    url(r'^docs/parsers/$', docs.parsers, name="docs_parsers"),
]

robox/models.py
from datetime import timedelta
import logging

from django.db import models
from django.db.transaction import atomic
from django.utils import timezone
from django.utils.datastructures import OrderedSet
from django.utils.functional import cached_property

from robox import parsing

_logger = logging.getLogger(__name__)


class DataFile(models.Model):
    upload_time = models.DateTimeField(auto_now_add=True)
    barcode = models.CharField(max_length=50)
    binary_file = models.ForeignKey('BinaryFile')
    format = models.CharField(max_length=20, default="None")

    @cached_property
    def headings(self):
        headings = OrderedSet()
        for entry in self.entry_set.all():
            for meta_data in entry.metadata_set.all():
                headings.add(meta_data.key)
        return headings

    def content(self):
        entry_data = []
        for entry in self.entry_set.all():
            data = {meta_data.key: meta_data.value for meta_data in entry.metadata_set.all()}
            entry_data.append([data[heading] for heading in self.headings])
        return entry_data

    def recent(self):
        return self.upload_time > timezone.now() - timedelta(seconds=30)

    @atomic
    def parse(self):
        # Delete any old entries (in case it is a reparse.
        Entry.objects.filter(data_file=self).delete()

        try:
            parsed_file = parsing.parse(self.binary_file.data)
        except parsing.RoboxParsingError:
            _logger.info("Unparsed file %s" % self.binary_file.name)
        else:
            self.format = parsed_file['parser']
            self.save()

            _logger.debug("File parsed: %s as %s" % (self.binary_file.name, self.format))

            for data in parsed_file['data']:
                entry = Entry.objects.create(data_file=self)
                for key, value in data.items():
                    MetaData.objects.create(entry=entry, key=key, value=value)


class BinaryFile(models.Model):
    name = models.CharField(max_length=64)
    data = models.BinaryField()

    def __str__(self):
        return self.name


class Entry(models.Model):
    data_file = models.ForeignKey(DataFile)


class MetaData(models.Model):
    entry = models.ForeignKey(Entry)
    key = models.CharField(max_length=50)
    value = models.CharField(max_length=50)

robox/forms.py
import logging

from django import forms

from robox.utils import validate_barcode

_logger = logging.getLogger(__name__)


class BarcodeField(forms.Field):
    def to_python(self, value):
        return value

    def validate(self, value):
        validate_barcode(value)


class UploadForm(forms.Form):
    barcode = BarcodeField()
    file = forms.FileField()

robox/views.py
import logging
import json

from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse, reverse_lazy
from django.db import DatabaseError
from django.db.transaction import atomic
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import FormView, DeleteView
import pika

from pika.exceptions import ConnectionClosed

from robox.forms import UploadForm, validate_barcode
from robox.models import File

_logger = logging.getLogger(__name__)


def index(request):
    files = File.objects.all().order_by('-upload_time')[:20]

    return render(request, "robox/index.html", {"files": files})


def search(request):
    barcode = request.GET.get('barcode')
    if barcode:
        return HttpResponseRedirect(reverse('robox:view', kwargs={'barcode': barcode}))
    else:
        return HttpResponseRedirect(reverse('robox:index'))


class UploadView(FormView):
    template_name = "robox/upload.html"
    form_class = UploadForm

    def form_valid(self, form):
        files = self.request.FILES
        barcode = form.cleaned_data['barcode']

        database_files = upload_files(barcode, [file for file_key in files.keys() for file in files.getlist(file_key)])

        return HttpResponseRedirect(reverse('robox:view', kwargs={'barcode': database_files[0].barcode}))


@atomic
def upload_files(barcode, files):
    """
    Atomically uploads a file to the database and parses it.
    :param barcode: The barcode for the file to be uploaded to.
    :param files: The Django files to be uploaded
    :return: The database model of the uploaded file.
    """
    barcode = barcode
    database_files = []

    for file in files:
        try:
            database_file = File.objects.create(
                file=file,
                barcode=barcode,
            )
            database_file.parse()
            database_files.append(database_file)
        except DatabaseError as err:
            try:
                # noinspection PyUnboundLocalVariable
                database_file.file.delete()
            except NameError:
                pass
            raise err

    try:
        connection = pika.BlockingConnection(pika.ConnectionParameters('localhost'))
        channel = connection.channel()
        channel.queue_declare(queue="upload_notifier")

        channel.basic_publish(exchange='',
                              routing_key='upload_notifier',
                              body=json.dumps({"barcode": barcode, "file_count": len(database_files)}))

        connection.close()
        _logger.debug("Sent message to message queue.")
    except ConnectionClosed:
        _logger.warning("rabbitmq server not responding.")

    return database_files


def view_by_barcode(request, barcode):
    barcode = barcode
    try:
        validate_barcode(barcode)
        files = File.objects.filter(barcode=barcode)

        return render(request, "robox/view.html", {'files': files, 'barcode': barcode})
    except ValidationError:
        return render(request, "robox/view.html", {'invalid': True, 'barcode': barcode})


def upload_by_barcode(request, barcode):
    files = request.FILES

    database_files = upload_files(barcode, [file for file_key in files.keys() for file in files.getlist(file_key)])

    return HttpResponseRedirect(reverse('robox:view', kwargs={'barcode': database_files[0].barcode}))


class FileDelete(DeleteView):
    model = File
    success_url = reverse_lazy('robox:index')

robox/views/api.py
import logging
from http import client

from django.core.exceptions import ValidationError
from django.db.models import Q
from django.db.transaction import atomic
from rest_framework import serializers
from rest_framework.mixins import ListModelMixin, CreateModelMixin
from rest_framework.pagination import LimitOffsetPagination
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from robox.models import DataFile
from robox.utils import upload_files, validate_barcode

_logger = logging.getLogger(__name__)


class EntryField(serializers.RelatedField):
    def to_representation(self, value):
        return {meta_data.key: meta_data.value for meta_data in value.metadata_set.all()}


class FileSerializer(serializers.ModelSerializer):
    data = EntryField(many=True, read_only=True, source='entry_set')

    class Meta:
        model = DataFile
        fields = ('barcode', 'format', 'upload_time', 'data')


class StandardPaginationClass(LimitOffsetPagination):
    default_limit = 10
    max_limit = 100


class FileViewSet(ListModelMixin, CreateModelMixin, GenericViewSet):
    serializer_class = FileSerializer
    pagination_class = StandardPaginationClass

    def get_queryset(self):
        queryset = DataFile.objects.all()

        barcodes = self.request.query_params.get("barcode")

        if barcodes:
            query_filter = None
            for barcode in barcodes.split(","):
                if query_filter:
                    query_filter |= Q(barcode__iexact=barcode)
                else:
                    query_filter = Q(barcode__iexact=barcode)
            queryset = queryset.filter(query_filter)

        return queryset

    @atomic()
    def create(self, request, *args, **kwargs):
        barcode = request.data.get('barcode')
        files = request.FILES

        try:
            validate_barcode(barcode)

            database_files = upload_files(barcode, [file for file in files.values()])

            return Response({"results": [FileSerializer(database_file).data for database_file in database_files]},
                            status=client.CREATED)
        except ValidationError:
            return Response({'error': 'Invalid barcode', 'barcode': barcode}, status=client.UNPROCESSABLE_ENTITY)

robox/views/docs.py
import os

from django.shortcuts import render

from mainsite import settings


def index(request):
    return render(request, "robox/docs/index.html")


def api(request):
    return render(request, "robox/docs/markdown.html", {
        'title': 'API docs',
        'markdown_content': "\n".join(open(os.path.join(settings.BASE_DIR, "robox/static/robox/docs/md/api.md")))
    })


def parsers(request):
    return render(request, "robox/docs/markdown.html", {
        'title': 'Parser docs',
        'markdown_content': "\n".join(open(os.path.join(settings.BASE_DIR, "robox/static/robox/docs/md/parsers.md")))
    })

robox/views/web.py
import logging

from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.encoding import smart_str
from django.views.generic import FormView, DeleteView

from robox.forms import UploadForm
from robox.models import DataFile, BinaryFile
from robox.utils import upload_files, validate_barcode

_logger = logging.getLogger(__name__)


def index(request):
    files = DataFile.objects.all().order_by('-upload_time')[:15]

    return render(request, "robox/web/index.html", {"files": files})


def search(request):
    barcode = request.GET.get('barcode')
    if barcode:
        return HttpResponseRedirect(reverse('view', kwargs={'barcode': barcode}))
    else:
        return HttpResponseRedirect(reverse('index'))


class UploadView(FormView):
    template_name = "robox/web/upload.html"
    form_class = UploadForm

    def form_valid(self, form):
        files = self.request.FILES
        barcode = form.cleaned_data['barcode']

        database_files = upload_files(barcode, [file for file_key in files.keys() for file in files.getlist(file_key)])

        return HttpResponseRedirect(reverse('view', kwargs={'barcode': database_files[0].barcode}))


def view_by_barcode(request, barcode):
    barcode = barcode
    try:
        validate_barcode(barcode)
        files = DataFile.objects.filter(barcode__iexact=barcode)

        return render(request, "robox/web/view.html", {'files': files, 'barcode': barcode})
    except ValidationError:
        return render(request, "robox/web/view.html", {'invalid': True, 'barcode': barcode})


def upload_by_barcode(request, barcode):
    files = request.FILES

    database_files = upload_files(barcode, [file for file_key in files.keys() for file in files.getlist(file_key)])

    return HttpResponseRedirect(reverse('view', kwargs={'barcode': database_files[0].barcode}))


class FileDelete(DeleteView):
    model = DataFile
    success_url = reverse_lazy('index')


def download_file(request, pk):
    file = get_object_or_404(BinaryFile, pk=pk)

    response = HttpResponse(content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(file.name)
    response.write(file.data)

    return response

robox/templates/robox/web/index.html
{% extends 'robox/base_generic.html' %}

{% block title %}Index{% endblock %}
{% block links %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "robox/web/css/index.css" %}"/>
{% endblock %}
{% block content %}
    <h3>Latest {{ files.count }} files:</h3>
    <div class="row container files">
        <div class="row">
            <h4 class="col-xs-2">Barcode</h4>
            <h4 class="col-xs-7">Filename</h4>
            {% load tz %}
            {% get_current_timezone as TIME_ZONE %}
            <h4 class="col-xs-2">Uploaded at ({{ TIME_ZONE }})</h4>
        </div>
        {% for file in files|dictsortreversed:"upload_time" %}
            <div class="row">
                <div class="col-xs-2">{{ file.barcode }}</div>
                <div class="col-xs-7">{{ file.binary_file.name }}</div>
                <div class="col-xs-2">{{ file.upload_time|date:'Y-m-d H:i:s' }}</div>
                <div class="col-xs-1"><a href="{% url "view" file.barcode %}" class="btn btn-default btn-xs">Show</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

robox/templates/robox/web/upload.html
{% extends 'robox/base_generic.html' %}

{% block title %}Upload{% endblock %}
{% block links %}
    {% load staticfiles %}
    <script src="{% static "robox/web/js/upload.js" %}"></script>
{% endblock %}
{% block content %}
    <h3>Upload:</h3>
    <form class="form-horizontal" action="{% url "upload" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.barcode.errors }}
        <div class="form-group">
            <label class="col-sm-1 control-label" for="id_barcode">Barcode</label>
            <div class="col-sm-3">
                <input id="id_barcode" name="barcode" class="form-control" placeholder="Barcode"
                       value="{% if form.barcode.value %}{{ form.barcode.value }}{% endif %}">
            </div>
        </div>
        {{ form.file.errors }}
        <div class="form-group">
            <label class="col-sm-1 control-label" for="id_file">Files</label>
            <div class="col-sm-3">
                <input id="id_file" name="file" type="file" multiple>
            </div>
        </div>
        <div class="col-sm-1"></div>
        <div>
            <input type="submit" value="Submit" class="btn btn-primary"/>
            <a href="{% url "index" %}" class="btn btn-default">Back</a>
        </div>
    </form>
{% endblock %}

robox/templates/robox/web/view.html
{% extends 'robox/base_generic.html' %}

{% block title %}Viewing: {{ barcode }}{% endblock %}
{% block links %}
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static "robox/web/css/view.css" %}"/>
    <script src="{% static "robox/web/js/view.js" %}"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-8">
            <h3>Viewing: {{ barcode }}</h3>
        </div>
    </div>

    {% if not invalid %}
        <div class="upload col-sm-4 pull-right">
            <h4>Upload:</h4>
            <form class="form-horizontal" action="{% url "upload" %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-3 control-label">Barcode</label>
                    <div class="col-sm-9">
                        <input id="id_barcode" name="barcode" class="form-control" readonly value="{{ barcode }}">
                    </div>
                </div>
                {{ form.file.errors }}
                <div class="form-group">
                    <label class="col-sm-3 control-label" for="id_file">Files</label>
                    <div class="col-sm-2">
                        <input id="id_file" name="file" type="file" multiple>
                    </div>
                </div>
                <div class="col-sm-3"></div>
                <div>
                    <input type="submit" value="Submit" class="btn btn-primary"/>
                </div>
            </form>
        </div>
    {% endif %}

    {% if invalid %}
        <h3>Invalid barcode</h3>
    {% else %}
        {% if files|length_is:'0' %}
            <h3>No files found.</h3>
        {% else %}
            {% for file in files|dictsortreversed:"upload_time" %}
                <div class="file {% if file.recent %}recent{% endif %}">
                    <div class="file-header ">
                        <h4 class="file-name">File: <a
                                href="{% url 'download' file.binary_file.pk %}">{{ file.binary_file.name }}</a>
                        </h4>
                        <h5>Format: {% if file.format != "None" %}{{ file.format }}{% else %}
                            <span class="text-danger">Unrecognised</span>{% endif %}</h5>
                        <h5>Uploaded at: {{ file.upload_time|date:'Y-m-d H:i:s' }}</h5>
                    </div>
                    <input class="toggle-content" id="file{{ file.id }}" type="checkbox">
                    <label for="file{{ file.id }}">
                        <span>&#9654; Expand</span>
                        <span>&#9660; Collapse</span>
                    </label>
                    <table class="file-content">
                        <tr>
                            {% for heading in file.headings %}
                                <th>{{ heading }}</th>
                            {% endfor %}
                        </tr>
                        {% for data in file.content %}
                            <tr>
                                {% for dataum in data %}
                                    <td>{{ dataum }}</td>
                                {% endfor %}
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% endfor %}
        {% endif %}
    {% endif %}
{% endblock %}